### ISSUE TITLE
Errors with Swift 5 - indexpath.row and UILabel!

### ISSUE THREAD

**Issue by manish-makwana** [carlosrojaso/swift101#1]
Hello, I'm following this tutorial with Swift 5 and have been able to get it working for the most part. But I'm stuck on the tableview function to generate UITableViewCells for each row at a specific index. Specifically, I get the following errors:

`Instance member 'row' cannot be used on type 'IndexPath'; did you mean to use a value of this type instead?`

`Using '!' is not allowed here; perhaps '?' was intended?`

This is from the following code:

        override func tableView(_ tableView: UITableView, cellForRowAt indexPath: IndexPath) -> UITableViewCell {
                let tempCell = tableView.dequeueReusableCell(withIdentifier: "listPrototypeCell", for: indexPath) as UITableViewCell
                let todoItem = todoItems[IndexPath.row]
                
                let cell = tempCell.textLabel as UILabel!
                cell.text = todoItem.itemName
        
                return tempCell
        }

Any suggestions on how to fix this?

**Comment by carlosrojaso** [comment]
mmm I think this is a fork. Maybe you can try:


_As mentioned before, we love feedback - please open issues about anything you feel is missing, or email the authors directly about questions or feedback at jadekler@gmail.com._
